### ISSUE TITLE
Protected ranges on generated sheets

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#13]
The number one problem is that volunteers accidentally erase important metadata, in particular the title of the piece (A1) or the column names with the source.

This can be solved with a protected range.
- `list_protected_range`: https://docs.gspread.org/en/v5.3.0/api.html#gspread.spreadsheet.Spreadsheet.list_protected_ranges
- `add_protected_range`: https://docs.gspread.org/en/v5.3.0/api.html#gspread.worksheet.Worksheet.add_protected_range

I think there should be a protected range on the first row and first column of every sheet, the the user can't edit.

**Comment by jlumbroso** [comment]
The error reporting is very accurate and useful!
![Screen Shot 2022-11-04 at 2 26 25 AM](https://user-images.githubusercontent.com/11770469/199906170-a3f48d86-c626-409a-881a-1e86e8aea6fc.png)
![Screen Shot 2022-11-04 at 2 20 36 AM](https://user-images.githubusercontent.com/11770469/199906189-86e36442-013f-4ccf-9a8c-2e3ca6927346.png)

**Comment by josephlou5** [comment]
Yes, this is a great idea.

**Comment by josephlou5** [comment]
Closed with merge.

**Comment by josephlou5** [comment]
This feature currently doesn't work, since the protected ranges are using the editors of the sheet as the editors of the protected range, which has no effect with respect to volunteers not being able to edit parts of each sheet.

**Comment by josephlou5** [comment]
Closed with commit d3003f9160b2358a1744276cc9b90b835a801da5.
