### ISSUE TITLE
Mention missing `spreadsheets.json` in log, when trying to export JSON data

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#14]
Following up on a Slack conversation about this, the point that when I accidentally deleted my `output/spreadsheets.json` file, I got an error message that wasn't enough to help me understand what I had done wrong.

![Screen Shot 2022-11-05 at 11 47 06 PM](https://user-images.githubusercontent.com/11770469/200153157-493b03b5-d0d7-4ced-b41e-363d8b50f0ae.png)

![22489EFD-DE89-4FCC-A4AE-6351374EEC6B](https://user-images.githubusercontent.com/11770469/200153158-6ea25818-e9c8-4dc8-938c-75e8c35a671c.png)

**Comment by josephlou5** [comment]
Resolved with commit 242ea00f7dbef6c2dd31225de4cd6f7abe9ffe43. Staged for v0.10.1.
