### ISSUE TITLE
values.sourcesColumnWidth does not seem to work in Roseingrave v1.1.0

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#27]
Currently, the template file is configured to have a source column width of 150, see here:
https://github.com/scarlatti/argos-muenster/blob/c52e13d3c8a28a8a3de3267c11d6181fcc92f0f8/input/template_definitions.json#L235

Unfortunately, the spreadsheets that were generated following:
```bash
pipenv run roseingrave create_sheet -r -vd input/volunteer_definitions.json
```
do not seem to take this into consideration, here is an example:
![Screenshot 2023-07-09 at 1 39 57 PM](https://github.com/scarlatti/roseingrave/assets/11770469/5e63a4fb-4165-4aeb-9255-47fa997e126f)

This can be resolved as usual using the `fix_column_widths.py` script:
![Screenshot 2023-07-09 at 1 42 02 PM](https://github.com/scarlatti/roseingrave/assets/11770469/f6672365-9196-46e8-be0f-ff4889a92b8b)

**Comment by josephlou5** [comment]
It seems that you have `volunteerSpreadsheet.resize` set to `true`, which causes each column (including the source columns) to be resized to fit its content.

**Comment by jlumbroso** [comment]
Thanks for clarifying! Will adjust the parameter to `false` and close this issue. I will reopen if there are any other issues.
